### ISSUE TITLE
[CURATOR-281] Usage of TestingServer fails when upgrading to 3.0

### ISSUE THREAD

**Issue by jira-importer** [apache/curator#801]
<p>If I upgrade from 2.9.2 to 3.0 and run my existing unit tests I get this error on all tests:</p>
<div class="preformatted panel" style="border-width: 1px;"><div class="preformattedContent panelContent">
<pre>org.scurator.TestGetChildren > initializationError FAILED
    java.lang.NoClassDefFoundError: org/testng/Assert
at org.apache.curator.test.TestingZooKeeperMain.blockUntilStarted(TestingZooKeeperMain.java:135)
at org.apache.curator.test.TestingZooKeeperServer.start(TestingZooKeeperServer.java:159)
at org.apache.curator.test.TestingServer.<init>(TestingServer.java:117)
at org.apache.curator.test.TestingServer.<init>(TestingServer.java:100)
at org.apache.curator.test.TestingServer.<init>(TestingServer.java:41)
at org.scurator.BaseSCuratorTest$class.beforeEach(BaseSCuratorTest.scala:33)
at org.scurator.TestGetChildren.org$scurator$SCuratorTestClient$$super$beforeEach(TestGetChildren.scala:14)
at org.scurator.SCuratorTestClient$class.beforeEach(SCuratorTestClient.scala:20)
at org.scurator.TestGetChildren.beforeEach(TestGetChildren.scala:14)
at org.scalatest.BeforeAndAfterEach$class.beforeEach(BeforeAndAfterEach.scala:154)
at org.scurator.TestGetChildren.beforeEach(TestGetChildren.scala:14)
at org.scalatest.BeforeAndAfterEach$class.beforeEach(BeforeAndAfterEach.scala:173)
at org.scurator.TestGetChildren.beforeEach(TestGetChildren.scala:14)
at org.scalatest.BeforeAndAfterEach$class.runTest(BeforeAndAfterEach.scala:253)
at org.scurator.TestGetChildren.runTest(TestGetChildren.scala:14)

Caused by:
java.lang.ClassNotFoundException: org.testng.Assert
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    ... 15 more
</pre>
</div></div>

<p>The code it points to is here: <br/>
<a href="https://github.com/apache/curator/blob/apache-curator-3.0.0/curator-test/src/main/java/org/apache/curator/test/TestingZooKeeperMain.java#L135" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/blob/apache-curator-3.0.0/curator-test/src/main/java/org/apache/curator/test/TestingZooKeeperMain.java#L135</a></p>

<p>Its caused because I am an external user from the project and testng is marked as provided here:<br/>
<a href="https://github.com/apache/curator/blob/apache-curator-3.0.0/curator-test/pom.xml#L53-L57" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/blob/apache-curator-3.0.0/curator-test/pom.xml#L53-L57</a></p>

<p>The only other place testng is used is BaseClassForTests.java, which makes sense. I propose using a standard java assertion here to avoid the dependency for those using TestingServer.</p>

---
<details><summary><i>Originally reported by <a title="Grant Henke" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=granthenke">granthenke</a>, imported from: <a href="https://issues.apache.org/jira/browse/CURATOR-281" target="_blank">Usage of TestingServer fails when upgrading to 3.0</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Mike Drob" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mdrob">mdrob</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2015-11-17T19:40:48+00:00
<li><b>imported</b>: 2025-01-21
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user granthenke opened a pull request:</p>

<p>    <a href="https://github.com/apache/curator/pull/119" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/119</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/CURATOR-281" title="Usage of TestingServer fails when upgrading to 3.0" class="issue-link" data-issue-key="CURATOR-281"><del>CURATOR-281</del></a>: Usage of TestingServer fails when upgrading to 3.0</p>

<p>    Replace testng assertion with java assertion</p>

<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/granthenke/curator" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/granthenke/curator</a> <a href="https://issues.apache.org/jira/browse/CURATOR-281" title="Usage of TestingServer fails when upgrading to 3.0" class="issue-link" data-issue-key="CURATOR-281"><del>CURATOR-281</del></a></p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/curator/pull/119.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/119.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #119</p>

<hr />
<p>commit c52d762990c5b62d90facb587fc06acd4b65ad24<br/>
Author: Grant Henke <granthenke@gmail.com><br/>
Date:   2015-11-13T04:40:27Z</p>

<p>    <a href="https://issues.apache.org/jira/browse/CURATOR-281" title="Usage of TestingServer fails when upgrading to 3.0" class="issue-link" data-issue-key="CURATOR-281"><del>CURATOR-281</del></a>: Usage of TestingServer fails when upgrading to 3.0</p>

<p>    Replace testng assertion with java assertion</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user madrob commented on the pull request:</p>

<p>    <a href="https://github.com/apache/curator/pull/119#issuecomment-156468211" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/119#issuecomment-156468211</a></p>

<p>    Doesn't that effectively remove the assertion, though? Java assertions are not enabled by default, you need to specify the `-ea` flag for that.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user granthenke commented on the pull request:</p>

<p>    <a href="https://github.com/apache/curator/pull/119#issuecomment-156472448" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/119#issuecomment-156472448</a></p>

<p>    Good point, I could instead throw an IllegalStateException if the result is not true</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user granthenke commented on the pull request:</p>

<p>    <a href="https://github.com/apache/curator/pull/119#issuecomment-157132796" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/119#issuecomment-157132796</a></p>

<p>    @madrob Does this follow up patch look better?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user granthenke closed the pull request at:</p>

<p>    <a href="https://github.com/apache/curator/pull/119" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/119</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rbellamy@pteradigm.com">rbellamy@pteradigm.com</a>:</i>
<p>When will this fix be released to Maven Central? I can see in the GitHub project that there are numerous <a href="https://github.com/apache/curator/releases" class="external-link" target="_blank" rel="nofollow noopener">source tarballs</a> with release tags, but there's nothing greater than 3.0.0 in Maven Central.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>Apache Curator is at 3.2.1 in Maven Central. Where are you looking? <a href="http://search.maven.org/#artifactdetails%7Corg.apache.curator%7Capache-curator%7C3.2.1%7Cpom" class="external-link" target="_blank" rel="nofollow noopener">http://search.maven.org/#artifactdetails%7Corg.apache.curator%7Capache-curator%7C3.2.1%7Cpom</a></p>
